language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
# # command to run tests, e.g. python setup.py test
before_script: pip install -r dev-requirements.txt
script:  make travis
notifications:
   on_success: change
   on_failure: always

branches:
   except:
      - uricore

env: TRAVIS_GH3="True"
